version: '3.8'

services:
  app:
    build: .
    container_name: backoffice-backend-app
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command: http --domain=${NGROK_DOMAIN} app:${PORT}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - app
