CREATE DATABASE JOB_MARKET;
USE JOB_MARKET;

CREATE TABLE ALUMNOS(
	ID				INT	AUTO_INCREMENT PRIMARY KEY,
    APELLIDOS 		VARCHAR(20) NOT NULL, 
    NOMBRES 		VARCHAR(20) NOT NULL, 
    GENERO 			CHAR(1) NOT NULL CHECK (GENERO IN ('M', 'F')),
    FECH_NACIMIENTO DATE NOT NULL, 
    TIPO_DOI 		CHAR(3) NOT NULL, 
    NUM_DOI 		VARCHAR(15) NOT NULL, 
    CURRICULUM 		TEXT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;

CREATE TABLE EMPRESAS (
    ID 				INT AUTO_INCREMENT PRIMARY KEY,
    RAZON_SOCIAL 	VARCHAR(60) NOT NULL,
    RUC 		 	CHAR(11) NOT NULL,
    LOGO 			TEXT NOT NULL, -- URL
    DIRECCION1 		VARCHAR(80) NOT NULL,
    DIRECCION2 		VARCHAR(80) NULL,
    RUBRO 			VARCHAR(60) NOT NULL,
    CONTACTO1 		VARCHAR(60) NOT NULL,
    TELEFONO1 		CHAR(9) NOT NULL,
    CORREO1 		VARCHAR(50) NOT NULL,
    CONTACTO2 		VARCHAR(60) NULL,
    TELEFONO2 		CHAR(9) NULL,
    CORREO2 		VARCHAR(50) NULL,
    CONTACTO3 		VARCHAR(60) NULL,
    TELEFONO3 		CHAR(9) NULL,
    CORREO3 		VARCHAR(50) NULL,
    is_active 		BOOLEAN NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;