CREATE DATABASE JOB_MARKET;
USE JOB_MARKET;

CREATE TABLE PROGRAMA_ESTUDIO(
	ID			INT	AUTO_INCREMENT PRIMARY KEY,
    NOMBRE		VARCHAR(100) NOT NULL,
    ESTADO		BOOLEAN NOT NULL,
	created_at 	DATETIME,
	updated_at 	DATETIME,
	deleted_at 	DATETIME
)ENGINE=INNODB;

CREATE TABLE TUTORES(
	ID				INT	AUTO_INCREMENT PRIMARY KEY,
    APELLIDOS 		VARCHAR(20) NOT NULL, 
    NOMBRES 		VARCHAR(20) NOT NULL, 
    GENERO 			CHAR(1) NOT NULL CHECK (GENERO IN ('M', 'F')),
    FECH_NACIMIENTO DATE NOT NULL, 
    TIPO_DOI 		CHAR(3) NOT NULL, 
    NUM_DOI 		VARCHAR(15) NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;

CREATE TABLE ALUMNOS(
	ID					INT	AUTO_INCREMENT PRIMARY KEY,
    APELLIDOS 			VARCHAR(20) NOT NULL, 
    NOMBRES 			VARCHAR(20) NOT NULL, 
    GENERO 				CHAR(1) NOT NULL CHECK (GENERO IN ('M', 'F')),
    FECH_NACIMIENTO 	DATE NOT NULL, 
    TIPO_DOI 			CHAR(3) NOT NULL, 
    NUM_DOI 			VARCHAR(15) NOT NULL,
    PROGRAMA_ESTUDIO_ID INT NOT NULL,
    ES_EGRESADO			BOOLEAN NOT NULL,
    CURRICULUM 			TEXT NULL,
    created_at 			DATETIME,
    updated_at 			DATETIME,
    deleted_at 			DATETIME,
    FOREIGN KEY (PROGRAMA_ESTUDIO_ID) REFERENCES PROGRAMA_ESTUDIO(ID)
)ENGINE=INNODB;

CREATE TABLE EMPRESAS (
    ID 				INT AUTO_INCREMENT PRIMARY KEY,
    RAZON_SOCIAL 	VARCHAR(60) NOT NULL,
    RUC 		 	CHAR(11) NOT NULL,
    LOGO 			TEXT NOT NULL,
    DIRECCION1 		VARCHAR(80) NOT NULL,
    DIRECCION2 		VARCHAR(80) NULL,
    RUBRO 			VARCHAR(60) NOT NULL,
    CONTACTO1 		VARCHAR(60) NOT NULL,
    TELEFONO1 		CHAR(9) NOT NULL,
    CORREO1 		VARCHAR(50) NOT NULL,
    CONTACTO2 		VARCHAR(60) NULL,
    TELEFONO2 		CHAR(9) NULL,
    CORREO2 		VARCHAR(50) NULL,
    CONTACTO3 		VARCHAR(60) NULL,
    TELEFONO3 		CHAR(9) NULL,
    CORREO3 		VARCHAR(50) NULL,
    is_active 		BOOLEAN NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;

CREATE TABLE OFERTAS (
    ID 					INT AUTO_INCREMENT PRIMARY KEY,
    EMPRESA_ID 			INT NOT NULL,
    TITULO 				VARCHAR(50) NOT NULL,
    DESCRIPCION 		TEXT NOT NULL,
    SUELDO 				SMALLINT UNSIGNED NULL,
    AD_HONOREM		    BOOLEAN NOT NULL,
    VIATICOS 			SMALLINT UNSIGNED NULL,
    BONOS 				SMALLINT UNSIGNED NULL,
    REQUISITOS 			TEXT NOT NULL,
    BENEFICIOS 			TEXT NOT NULL,
    NUM_VACANTES 		TINYINT UNSIGNED NULL, -- MAXIMO 255
    FECHA_PUBLICACION 	DATETIME NULL,
    FECHA_CIERRE 		DATETIME NULL,
    CONTACTO			VARCHAR(60) NULL,
    CORREO				VARCHAR(50) NULL,
    TELEFONO			VARCHAR(50) NULL,
    created_at 		    DATETIME,
    updated_at 		    DATETIME,
    deleted_at 		    DATETIME,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID)
) ENGINE=INNODB;

CREATE TABLE POSTULACIONES (
    ID 	INT AUTO_INCREMENT PRIMARY KEY,
    OFERTA_ID INT NOT NULL,
    ALUMNO_ID INT NOT NULL,
    FECHA_POSTULACION DATETIME NOT NULL,
    ESTADO_RESPUESTA ENUM('PENDING','APPROVED','REJECTED') NOT NULL,
    DOC_ADJUNTO1 TEXT NOT NULL,
    DOC_ADJUNTO2 TEXT NULL,
    DOC_ADJUNTO3 TEXT NULL,
    DOC_ADJUNTO4 TEXT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME,
    FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS(ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ID)
) ENGINE=INNODB;

CREATE TABLE USUARIOS(
	ID 				INT AUTO_INCREMENT PRIMARY KEY,
    TIPO 			ENUM('STUDENT','COMPANY','ADMIN', 'TUTOR') NOT NULL,
    USERNAME 		VARCHAR(18) NOT NULL,
    USERPASS 		TEXT NOT NULL,
    EMPRESA_ID 		INT NULL,
    ALUMNO_ID 		INT NULL,
    TUTOR_ID		INT NULL,
    is_active 		BOOLEAN NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ID),
    FOREIGN KEY (TUTOR_ID) REFERENCES TUTORES(ID)
)ENGINE=INNODB;
