INSERT INTO ALUMNOS (APELLIDOS, NOMBRES, GENERO, FECH_NACIMIENTO, TIPO_DOI, NUM_DOI, CURRICULUM, created_at, updated_at) 
VALUES ('Garcia', 'Juan', 'M', '1995-03-12', 'DNI', '12345678', 'Ingeniero en Sistemas', now(), now()), 
       ('Martinez', 'Maria', 'F', '1998-07-22', 'CE', '87654321', 'Licenciada en Educación', now(), now()), 
       ('Lopez', 'Carlos', 'M', '1990-11-05', 'DNI', '56789012', 'Desarrollador de Software', now(), now());
       
INSERT INTO EMPRESAS (RAZON_SOCIAL, RUC, LOGO, DIRECCION1, DIRECCION2, RUBRO, CONTACTO1, TELEFONO1, CORREO1, CONTACTO2, TELEFONO2, CORREO2, CONTACTO3, TELEFONO3, CORREO3, is_active, created_at, updated_at) VALUES
(
    'Tecnologías Innovadoras S.A.', 
    '20567893451', 
    'https://ejemplo.com/logo1.png', 
    'Av. La Marina 1234', 
    'Piso 5, Oficina 502', 
    'Tecnología y Software', 
    'Juan Pérez', 
    '987654321', 
    'jperez@tecninnovadoras.com', 
    'María Gómez', 
    '912345678', 
    'mgomez@tecninnovadoras.com', 
    NULL, 
    NULL, 
    NULL, 
    TRUE, 
    NOW(), 
    NOW()
),
(
    'Alimentos Saludables E.I.R.L.', 
    '20123456789', 
    'https://ejemplo.com/logo2.jpg', 
    'Calle Los Olivos 456', 
    NULL, 
    'Alimentación y Bebidas', 
    'Carlos Rodríguez', 
    '976543218', 
    'crodriguez@alimentossaludables.com', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    TRUE, 
    NOW(), 
    NOW()
),
(
    'Consultoría Empresarial & Asociados S.A.C.', 
    '20654321876', 
    'https://ejemplo.com/logo3.svg', 
    'Jr. Puno 789', 
    'Edificio Torre Azul', 
    'Consultoría Empresarial', 
    'Ana Vargas', 
    '934567812', 
    'avargas@consultoriaempresarial.com', 
    'Luis Fernández', 
    '945678123', 
    'lfernandez@consultoriaempresarial.com', 
    'Sofía Mendoza', 
    '956781234', 
    'smendoza@consultoriaempresarial.com', 
    TRUE, 
    NOW(), 
    NOW()
);

