CREATE VIEW VIEW_OFERTAS_GUARDADAS AS
SELECT 
OG.*,
E.ID AS EMPRESA_ID, E.RAZON_SOCIAL, E.DIRECCION1,
O.TITULO, O.deleted_at AS oferta_deleted_at
FROM OFERTAS_GUARDADAS AS OG
INNER JOIN OFERTAS AS O
ON O.ID = OG.OFERTA_ID
INNER JOIN EMPRESAS AS E
ON E.ID = O.EMPRESA_ID;