CREATE VIEW VIEW_ALUMNOS_CON_PROGRAMA_ESTUDIO AS
SELECT 
A.ID, A.APELLIDOS, A.NOMBRES, 
 CASE 
    WHEN A.GENERO = 'M' THEN 'MASCULINO'
    WHEN A.GENERO = 'F' THEN 'FEMENINO'
  END AS GENERO,
A.FECH_NACIMIENTO, A.TIPO_DOI, A.NUM_DOI,
A.created_at, A.updated_at, A.deleted_at,
PE.NOMBRE AS PROGRAMA_ESTUDIO
FROM ALUMNOS AS A
INNER JOIN PROGRAMA_ESTUDIO AS PE
ON PE.ID = A.PROGRAMA_ESTUDIO_ID;