CREATE VIEW VIEW_OFERTAS_CON_INFO_PE_EMPRESAS AS
SELECT 
    O.ID, O.TITULO, O.DESCRIPCION, O.SUELDO, O.AD_HONOREM, O.VIATICOS, O.BONOS, O.REQUISITOS, O.BENEFICIOS, O. NUM_VACANTES, O.FECHA_PUBLICACION, O.FECHA_CIERRE, O.CONTACTO, O.CORREO, O.TELEFONO, O.EMPRESA_ID, 
    O.created_at AS oferta_created_at, O.deleted_at as oferta_deleted_at,
    E.RAZON_SOCIAL, E.DIRECCION1,
    OPE.PROGRAMA_ESTUDIO_ID, 
    OPE.created_at, OPE.updated_at, OPE.deleted_at
FROM OFERTA_PROGRAMA_ESTUDIO AS OPE
INNER JOIN OFERTAS AS O 
	ON OPE.OFERTA_ID = O.ID
INNER JOIN EMPRESAS AS E
	ON O.EMPRESA_ID = E.ID;