CREATE VIEW VIEW_POSTULACIONES_OFERTA_EMPRESA AS
SELECT 
P.ID, P.OFERTA_ID, P.ALUMNO_ID, P.FECHA_POSTULACION, P.ESTADO_RESPUESTA,
O.EMPRESA_ID, O.TITULO, O.FECHA_PUBLICACION, O.FECHA_CIERRE,
E.RAZON_SOCIAL, E.RUBRO,
P.created_at, P. updated_at, P.deleted_at
FROM POSTULACIONES AS P
INNER JOIN ALUMNOS AS A
ON P.ALUMNO_ID = A.ID
INNER JOIN OFERTAS AS O
ON P.OFERTA_ID = O.ID
INNER JOIN EMPRESAS AS E
ON O.EMPRESA_ID = E.ID;