CREATE VIEW VIEW_POSTULACIONES_POR_EMPRESA_ID AS
SELECT 
P.ID, P.OFERTA_ID, P.ALUMNO_ID, P.FECHA_POSTULACION, P.ESTADO_RESPUESTA, P.DOC_ADJUNTO1, P.created_at, P. updated_at, P.deleted_at,
A.APELLIDOS, A.NOMBRES, A.TIPO_DOI, A.NUM_DOI,
O.EMPRESA_ID, O.TITULO, O.FECHA_PUBLICACION, O.FECHA_CIERRE
FROM POSTULACIONES AS P
INNER JOIN ALUMNOS AS A
ON P.ALUMNO_ID = A.ID
INNER JOIN OFERTAS AS O
ON P.OFERTA_ID = O.ID;